routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('guest:admin')->group(function (){
    Route::get('login', 'AuthController@getLogin')->name('login');
    Route::post('login', 'AuthController@doLogin')->name('do.login');
});

Route::middleware('auth:admin')->group(function (){

    Route::get('logout', 'AuthController@doLogout')->name('do.logout');

    Route::resource('left-stuff', 'LeftStuffController');
    Route::get('left-stuff/load/datatables', 'LeftStuffController@loadDatatables')->name('left-stuff.datatables');

    Route::resource('student-card', 'StudentCardController');
    Route::get('student-card/load/datatables', 'StudentCardController@loadDatatables')->name('student-card.datatables');

    Route::resource('admin', 'AdminController');
    Route::patch('admin/setup-akun/{id}', 'AdminController@setupAkun');

    Route::group(['prefix' => 'setting'], function (){
        Route::get('/', 'SettingController@index')->name('setting.index');
        Route::resource('location', 'LocationController');
        Route::get('location/load/datatables', 'LocationController@loadDatatables')->name('location.datatables');

        Route::resource('prodi', 'ProdiController');
        Route::get('prodi/load/datatables', 'ProdiController@loadDatatables')->name('prodi.datatables');
    });

    Route::get('list/location', 'LocationController@listLocation')->name('list.location');
    Route::get('list/prodi', 'ProdiController@listProdi')->name('list.prodi');
});

resources/views/pages/admin/blade-js/admin-master.blade.php
<script type="text/javascript">
    var url_admin;
    $(document).ready(function () {

    });
    function addAdmin() {
        $('[name=_method]').val("POST")
        url_admin = "{{ route('admin.store') }}"
        $("#modal-admin-title").html("Add New Administrator")
        $("#modal-admin-btn").prop("class", "btn btn-success")
        $("#modal-admin-btn").html("SAVE")
        $('.admin-modal form')[0].reset()
        $("#password_area").html('<div class="form-group">\n' +
            '                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Password*</label>\n' +
            '                        <div class="col-md-4 col-sm-4 col-xs-12">\n' +
            '                            <input type="text" class="form-control" value="12345678 (default)" readonly="readonly">\n' +
            '                        </div>\n' +
            '                    </div>')
        $('.admin-modal').modal("show")
    }
    function editAdmin(id) {
        $('[name=_method]').val("PATCH")
        url_admin = "{{ url('admin') }}/" + id
        $("#modal-admin-title").html("Add New admin")
        $("#modal-admin-btn").prop("class", "btn btn-info")
        $("#modal-admin-btn").html("UPDATE")
        $("#password_area").html("")

        $.ajax({
            type: "GET",
            url: "{{ url('admin') }}/" + id + '/edit',
            dataType: "JSON",
            success: function (data) {
                $('[name=name]').val(data.name)
                $('[name=phone]').val(data.phone)
                $('[name=address]').val(data.address)
                $("#status [value=" + data.status + "]").prop('selected','selected')
                $('[name=email]').val(data.email)
                $('.admin-modal').modal("show")
            },
            error: function () {
                alert("Not Found")
            }
        });
    }
    function destroyAdmin(id) {
        if (confirm("Delete Permanently and All Activity (Warning!) ?")){
            $.ajax({
                type: "POST",
                url: "{{ url('admin') }}/" + id,
                data: {_method: "DELETE", _token: "{{ csrf_token() }}"},
                success: function (data) {
                    window.location.reload()
                },
                error: function () {
                    alert("Something Wrong !")
                }
            })
        }
    }
    $(function () {
        $('.admin-modal form').validator().on('submit', function (e) {
            if (!e.isDefaultPrevented()){
                $.ajax({
                    type: "POST",
                    url: url_admin,
                    data: $('.admin-modal form').serialize(),
                    success: function () {
                        $('.admin-modal').modal("hide")
                        $('.admin-modal form')[0].reset()
                        window.location.reload()
                    },
                    error: function () {
                        alert("Something Wrong !")
                    }
                });
                return false
            }
        });
    });
</script>

resources/views/pages/admin/blade-js/admin.blade.php
<script type="text/javascript">
    var url_admin;
    $(document).ready(function () {

    });
    function setupAkun() {
        $('[name=_method]').val("PATCH")
        url_admin = "{{ url('admin/setup-akun') }}/" + {{ auth('admin')->user()->id }}
        $("#modal-admin-title").html("Add New admin")
        $("#modal-admin-btn").prop("class", "btn btn-info")
        $("#modal-admin-btn").html("UPDATE")
        $("#password_area").html('<div class="form-group">\n' +
            '                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Password*</label>\n' +
            '                        <div class="col-md-4 col-sm-4 col-xs-12">\n' +
            '                            <input type="password" name="password" class="form-control" minlength="8" maxlength="100" required="required">\n' +
            '                        </div>\n' +
            '                    </div>')

        $.ajax({
            type: "GET",
            url: "{{ url('admin') }}/" + {{ auth('admin')->user()->id }} + '/edit',
            dataType: "JSON",
            success: function (data) {
                $('[name=name]').val(data.name)
                $('[name=phone]').val(data.phone)
                $('[name=address]').val(data.address)
                $('[name=email]').val(data.email)
                $('.admin-modal').modal("show")
            },
            error: function () {
                alert("Not Found")
            }
        });
    }
    $(function () {
        $('.admin-modal form').validator().on('submit', function (e) {
            if (!e.isDefaultPrevented()){
                $.ajax({
                    type: "POST",
                    url: url_admin,
                    data: $('.admin-modal form').serialize(),
                    success: function () {
                        $('.admin-modal').modal("hide")
                        $('.admin-modal form')[0].reset()
                        window.location.reload()
                    },
                    error: function () {
                        alert("Something Wrong !")
                    }
                });
                return false
            }
        });
    });
</script>