routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('guest:admin')->group(function (){
    Route::get('login', 'AuthController@getLogin')->name('login');
    Route::post('login', 'AuthController@doLogin')->name('do.login');
});

Route::middleware('auth:admin')->group(function (){

    Route::get('logout', 'AuthController@doLogout')->name('do.logout');

    Route::resource('left-stuff', 'LeftStuffController');
    Route::get('left-stuff/load/datatables', 'LeftStuffController@loadDatatables')->name('left-stuff.datatables');

    Route::resource('student-card', 'StudentCardController');
    Route::get('student-card/load/datatables', 'StudentCardController@loadDatatables')->name('student-card.datatables');

    Route::resource('admin', 'AdminController');
    Route::patch('admin/setup-akun/{id}', 'AdminController@setupAkun');

    Route::group(['prefix' => 'setting'], function (){
        Route::get('/', 'SettingController@index')->name('setting.index');
        Route::resource('location', 'LocationController');
        Route::get('location/load/datatables', 'LocationController@loadDatatables')->name('location.datatables');

        Route::resource('prodi', 'ProdiController');
        Route::get('prodi/load/datatables', 'ProdiController@loadDatatables')->name('prodi.datatables');
    });

    Route::get('list/location', 'LocationController@listLocation')->name('list.location');
    Route::get('list/prodi', 'ProdiController@listProdi')->name('list.prodi');
});

resources/views/templates/partials/footer.blade.php
<footer>
    <div class="pull-right">
        ©2018 Info-Lab STMIK-STIE ASIA, Malang
    </div>
    <div class="clearfix"></div>
</footer>

resources/views/templates/partials/head.blade.php
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ env('APP_NAME') }}</title>

    <!-- Bootstrap -->
    <link href="{{ asset('assets/vendors/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{ asset('assets/vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    <!-- Select2 -->
    <link href="{{ asset('assets/vendors/select2/dist/css/select2.min.css') }}" rel="stylesheet">

    <!-- NProgress -->
    <link href="{{ asset('assets/vendors/nprogress/nprogress.css') }}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{{ asset('assets/vendors/iCheck/skins/flat/green.css') }}" rel="stylesheet">
    <!-- Datatables-->
    <link href="{{ asset('assets/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
    <!-- bootstrap-progressbar -->
    <link href="{{ asset('assets/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css') }}" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="{{ asset('assets/build/css/custom.min.css') }}" rel="stylesheet">
</head>

resources/views/templates/partials/menu-footer-buttons.blade.php
<div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="">
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Settings">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
</div>

resources/views/templates/partials/script.blade.php
<!-- jQuery -->
<script src="{{ asset('assets/vendors/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap -->
<script src="{{ asset('assets/vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- Bootstrap Validator -->
<script src="{{ asset('assets/vendors/bootstrap-validator/validator.min.js') }}"></script>
<!-- Select2 -->
<script src="{{ asset('assets/vendors/select2/dist/js/select2.full.min.js') }}"></script>
<!-- NProgress -->
<script src="{{ asset('assets/vendors/nprogress/nprogress.js') }}"></script>
<!-- bootstrap-progressbar -->
<script src="{{ asset('assets/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') }}"></script>
<!-- Datatables-->
<script src="{{ asset('assets/vendors/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
<!-- Custom Theme Scripts -->
<script src="{{ asset('assets/build/js/custom.min.js') }}"></script>

resources/views/templates/partials/sidebar-menu.blade.php
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <h3>Menu</h3>
        <ul class="nav side-menu">
            <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="{{ route('student-card.index') }}"><i class="fa fa-credit-card"></i> Student Card</a></li>
            <li><a href="{{ route('left-stuff.index') }}"><i class="fa fa-shopping-basket"></i> Left Stuff</a></li>
            <li><a><i class="fa fa-folder-open-o"></i> Inventory <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="#">Master Inventories</a></li>
                    <li><a href="#">Transaction</a></li>
                </ul>
            </li>
            <li><a href="#"><i class="fa fa-certificate"></i> Certification</a></li>
            <li><a href="#"><i class="fa fa-calendar"></i> Schedule</a></li>
            <li><a><i class="fa fa-pencil"></i> Blog <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                    <li><a href="#">News & Information</a></li>
                    <li><a href="#">Staff</a></li>
                </ul>
            </li>
            <li><a href="{{ route('setting.index') }}"><i class="fa fa-cogs"></i> Setting</a></li>
            <li><a href="{{ route('admin.index') }}"><i class="fa fa-user"></i> Administrator</a></li>
        </ul>
    </div>
</div>

resources/views/templates/partials/top-navigation.blade.php
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="{{ asset('images/admin-lembaga.png') }}" alt="">{{ auth('admin')->user()->name }}</text>
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="{{ route('admin.index') }}"><i class="fa fa-user pull-right"></i> Pengaturan Akun</a></li>
                        <li><a href="{{ route('do.logout') }}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>