routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('guest:admin')->group(function (){
    Route::get('login', 'AuthController@getLogin')->name('login');
    Route::post('login', 'AuthController@doLogin')->name('do.login');
});

Route::middleware('auth:admin')->group(function (){

    Route::get('logout', 'AuthController@doLogout')->name('do.logout');

    Route::resource('left-stuff', 'LeftStuffController');
    Route::get('left-stuff/load/datatables', 'LeftStuffController@loadDatatables')->name('left-stuff.datatables');

    Route::resource('student-card', 'StudentCardController');
    Route::get('student-card/load/datatables', 'StudentCardController@loadDatatables')->name('student-card.datatables');

    Route::resource('admin', 'AdminController');
    Route::patch('admin/setup-akun/{id}', 'AdminController@setupAkun');

    Route::group(['prefix' => 'setting'], function (){
        Route::get('/', 'SettingController@index')->name('setting.index');
        Route::resource('location', 'LocationController');
        Route::get('location/load/datatables', 'LocationController@loadDatatables')->name('location.datatables');

        Route::resource('prodi', 'ProdiController');
        Route::get('prodi/load/datatables', 'ProdiController@loadDatatables')->name('prodi.datatables');
    });

    Route::get('list/location', 'LocationController@listLocation')->name('list.location');
    Route::get('list/prodi', 'ProdiController@listProdi')->name('list.prodi');
});

app/StudentCard.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class StudentCard extends Model
{
    protected $fillable = [
        'nim', 'name', 'prodi_id', 'place_of_birth', 'date_of_birth', 'address', 'city', 'phone', 'etc', 'photo_image',
        'photo_number', 'card_status', 'admin_id', 'print_status', 'taken_status', 'admin_taken_id', 'taken_at'
    ];

    public function prodi()
    {
        return $this->belongsTo(Prodi::class);
    }

    public function admin()
    {
        return $this->belongsTo(Admin::class);
    }
}

app/Http/Controllers/StudentCardController.php
<?php

namespace App\Http\Controllers;

use App\Admin;
use App\Prodi;
use App\StudentCard;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class StudentCardController extends Controller
{
    public function index()
    {
        $prodi = Prodi::all(['id','prodi']);
        $admin = Admin::all('id','name');
        return view('pages.student-card.index', compact('prodi','admin'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        return StudentCard::create([
            'nim' => $request->nim,
            'name' => $request->name,
            'prodi_id' => $request->prodi_id,
            'place_of_birth' => $request->place_of_birth,
            'date_of_birth' => $request->date_of_birth,
            'address' => $request->address,
            'city' => $request->city,
            'phone' => $request->phone,
            'etc' => $request->etc,
            'photo_number' => $request->photo_number,
            'card_status' => $request->card_status,
            'admin_id' => auth('admin')->user()->id,
            'print_status' => $request->print_status,
            'taken_status' => $request->taken_status,
        ]);
    }

    public function edit($id)
    {
        $student_card = StudentCard::find($id);
        $student_card->admin_id = $student_card->admin->name;
        if (isset($student_card->admin_taken_id)) {
            $student_card->admin_taken_id = Admin::find($student_card->admin_taken_id)->name;
        }

        return response()->json($student_card);
    }

    public function update(Request $request, StudentCard $student_card)
    {

        if ($request->taken_status == 1) {
            $request->print_status = 1;
            if (!isset($student_card->admin_taken_id)) {
                $request->admin_taken_id = auth('admin')->user()->id;
            } else {
                $request->admin_taken_id = $student_card->admin_taken_id;
            }
            $request->taken_at = Carbon::now();
        } elseif ($request->taken_status == 0) {
            $request->admin_taken_id = $request->taken_at = null;
        }

        $student_card->update([
            'nim' => $request->nim,
            'name' => $request->name,
            'prodi_id' => $request->prodi_id,
            'place_of_birth' => $request->place_of_birth,
            'date_of_birth' => $request->date_of_birth,
            'address' => $request->address,
            'city' => $request->city,
            'phone' => $request->phone,
            'etc' => $request->etc,
            'photo_number' => $request->photo_number,
            'card_status' => $request->card_status,
            'print_status' => $request->print_status,
            'taken_status' => $request->taken_status,
            'admin_taken_id' => $request->admin_taken_id,
            'taken_at' => $request->taken_at,
        ]);
    }

    public function destroy($id)
    {
        return StudentCard::destroy($id);
    }

    public function loadDatatables(Request $request)
    {
        $filter = $this->filterDatatables($request);

        $student_card = StudentCard::select(['id', 'nim', 'name', 'prodi_id', 'print_status', 'taken_status'])
            ->where($filter)
            ->get();

        foreach ($student_card as $card) {
            $card->prodi_id = Prodi::find($card->prodi_id)->prodi;
        }
        return DataTables::of($student_card)
            ->addColumn('actions', function ($student_card) {
                return '
                <a onclick="printStudentCard(' . $student_card->id . ')" class="btn btn-xs"><i class="fa fa-print text-warning"></i></a>
                <a onclick="editStudentCard(' . $student_card->id . ')" class="btn btn-xs"><i class="fa fa-pencil text-primary"></i></a>
                <a onclick="destroyStudentCard(' . $student_card->id . ')" class="btn btn-xs"><i class="fa fa-trash text-danger"></i></a>
                ';
            })
            ->rawColumns(['actions'])
            ->make(true);
    }

    private function filterDatatables($request) //stupid code //ndang perbaiki
    {
        $filter = [];
        if ($request->prodi_id != "All") {
            $filter ['prodi_id'] = $request->prodi_id;
        }
        if ($request->admin_id != "All") {
            $filter ['admin_id'] = $request->admin_id;
        }
        if ($request->print_status != "All") {
            $filter ['print_status'] = $request->print_status;
        }
        if ($request->card_status != "All") {
            $filter ['card_status'] = $request->card_status;
        }
        if ($request->admin_taken_id != "All") {
            $filter ['admin_taken_id'] = $request->admin_taken_id;
        }
        if ($request->taken_status != "All") {
            $filter ['taken_status'] = $request->taken_status;
        }
        return $filter;
    }
}

resources/views/pages/student-card/blade-js/student-card.blade.php
<script type="text/javascript">
    var student_card_dt;
    var url_student_card;
    $(document).ready(function () {
        $('[name=prodi_id_filter],[name=admin_id_filter],[name=print_status_filter],[name=card_status_filter],[name=admin_taken_id_filter],[name=taken_status_filter]').select2()
    });
    function loadDatatables() {
        student_card_dt = $("#student_card_datatables").DataTable({
            processing: true,
            serverSide: true,
            destroy: true,
            // order: [[3, 'asc'], [4, 'asc']],
            ajax: {
                type: "GET",
                url: "{{route('student-card.datatables')}}",
                data: {
                    prodi_id:$('[name=prodi_id_filter]').val(),
                    admin_id:$('[name=admin_id_filter]').val(),
                    print_status:$('[name=print_status_filter]').val(),
                    card_status:$('[name=card_status_filter]').val(),
                    admin_taken_id:$('[name=admin_taken_id_filter]').val(),
                    taken_status:$('[name=taken_status_filter]').val()
                }
            },
            columns: [
                {data: 'nim', name: 'nim', class: 'text-center'},
                {data: 'name', name: 'name'},
                {data: 'prodi_id', name: 'prodi_id', class: 'text-center'},
                {
                    data: 'print_status', class: 'text-center',
                    render: function (data, type, row) {
                        if (row.print_status === "0") {
                            return '<label class="label label-warning">Not Printed</label>'
                        } else if (row.print_status === "1") {
                            return '<label class="label bg-green">Printed</label>'
                        }
                    }
                },
                {
                    data: 'taken_status', class: 'text-center',
                    render: function (data, type, row) {
                        if (row.taken_status === "0") {
                            return '<label class="label bg-orange">Have Not Taken</label>'
                        } else if (row.taken_status === "1") {
                            return '<label class="label bg-green">Taken</label>'
                        }
                    }
                },
                {data: 'actions', name: 'actions', class: 'text-center', orderable: false}
            ]
        });
    }
    function addStudentCard() {
        $('[name=_method]').val("POST")
        url_student_card = "{{ route('student-card.store') }}"
        $("#prodi_id_area").html("");
        listProdi()
        $("#modal-student-card-title").html("Add Student Card")
        $("#modal-student-card-button").prop("class", "btn btn-success")
        $("#modal-student-card-button").html("SAVE")
        $('.student-card-modal form')[0].reset()
        $('.student-card-modal').modal("show")
    }
    function editStudentCard(id) {
        $('[name=_method]').val("PATCH")
        url_student_card = "{{ url('student-card') }}/" + id
        $("#prodi_id_area").html("");
        listProdi()
        $("#modal-student-card-title").html("Edit Student Card")
        $("#modal-student-card-button").prop("class", "btn btn-info")
        $("#modal-student-card-button").html("UPDATE")

        $.ajax({
            type: "GET",
            url: "{{ url('student-card')}}/" + id + '/edit',
            dataType: "JSON",
            success: function (data) {
                $('[name=nim]').val(data.nim)
                $('[name=name]').val(data.name)
                $("#prodi_id_area option[value=" + data.prodi_id + "]").prop('selected','selected')
                $('[name=place_of_birth]').val(data.place_of_birth)
                $('[name=date_of_birth]').val(data.date_of_birth) // error
                $('[name=address]').val(data.address) // error
                $('[name=city]').val(data.city) // error
                $('[name=phone]').val(data.phone) // error
                $('[name=etc]').val(data.etc) // error
                $('[name=photo_number]').val(data.photo_number) // error
                $("#card_status option[value=" + data.card_status + "]").prop('selected','selected')
                $("#admin").val(data.admin_id)
                $("#created_at").val(data.created_at)
                $("#print_status option[value=" + data.print_status + "]").prop('selected','selected')
                $("#taken_status option[value=" + data.taken_status + "]").prop('selected','selected')
                $("#admin_taken").val(data.admin_taken_id)
                $("#taken_at").val(data.taken_at)

                $('.student-card-modal').modal("show")
            },
            error: function () {
                alert("Something Wrong !")
            }
        });

    }
    $(function () {
        $('.student-card-modal form').validator().on('submit', function (e) {
            if (!e.isDefaultPrevented()){
                $.ajax({
                    type: "POST",
                    url: url_student_card,
                    data: $('.student-card-modal form').serialize(),
                    success: function () {
                        $('.student-card-modal').modal("hide")
                        $('.student-card-modal form')[0].reset()
                        student_card_dt.ajax.reload();
                    },
                    error: function () {
                        alert("Something Wrong !")
                    }
                });
            }
            return false
        });
    });
    function destroyStudentCard(id) {
        if (confirm("Delete Permanently ?")){
            $.ajax({
                type: "POST",
                url: "{{ url('student-card') }}" + "/" + id,
                data: {_method: "DELETE", _token: "{{ csrf_token() }}"},
                success: function (data) {
                    student_card_dt.ajax.reload()
                },
                error: function () {
                    alert("Something Wrong !")
                }
            })
        }
    }
    function listProdi() {
        $.ajax({
            type: "GET",
            url: "{{ route('list.prodi') }}",
            success: function (data) {
                $.each(data, function (key, value) {
                    $("#prodi_id_area").html($("#prodi_id_area").html() + '<option value="' + value.id + '">' + value.prodi +'</option>')
                });
            }
        });
    }
</script>